version: '3.8'
services:
  MewbieClient:
    image: python:latest
    container_name: mewbie_client
    volumes:
    - ./mewbie_client.py:/app/mewbie_client.py
    - ./client_requirements.txt:/app/client_requirements.txt
    - ./new_trace_details_data.pkl:/app/trace_details_data.pkl
    - ./enrichment_runs/new_test_run/all_trace_packets.json:/app/all_trace_packets.json
    working_dir: /app
    environment:
    - CONTAINER_NAME=mewbie_client
    command: sh -c "pip install -r client_requirements.txt && tail -f /dev/null"
    networks:
    - mewbie_network
  MongoDB-0_n4876:
    image: mongo:latest
    container_name: n4876
    ports:
    - 27017:27017
    networks:
    - mewbie_network
  Python-0_n3324:
    image: python:latest
    container_name: n3324
    volumes:
    - ./sl_test.py:/app/sl_test.py
    - ./sl_requirements.txt:/app/sl_requirements.txt
    working_dir: /app
    environment:
    - CONTAINER_NAME=n3324
    command: sh -c "pip install -r sl_requirements.txt && python sl_test.py"
    networks:
    - mewbie_network
  Python-1_n806:
    image: python:latest
    container_name: n806
    volumes:
    - ./sl_test.py:/app/sl_test.py
    - ./sl_requirements.txt:/app/sl_requirements.txt
    working_dir: /app
    environment:
    - CONTAINER_NAME=n806
    command: sh -c "pip install -r sl_requirements.txt && python sl_test.py"
    networks:
    - mewbie_network
  Python-2_n1929:
    image: python:latest
    container_name: n1929
    volumes:
    - ./sl_test.py:/app/sl_test.py
    - ./sl_requirements.txt:/app/sl_requirements.txt
    working_dir: /app
    environment:
    - CONTAINER_NAME=n1929
    command: sh -c "pip install -r sl_requirements.txt && python sl_test.py"
    networks:
    - mewbie_network
  Python-3_n3732:
    image: python:latest
    container_name: n3732
    volumes:
    - ./sl_test.py:/app/sl_test.py
    - ./sl_requirements.txt:/app/sl_requirements.txt
    working_dir: /app
    environment:
    - CONTAINER_NAME=n3732
    command: sh -c "pip install -r sl_requirements.txt && python sl_test.py"
    networks:
    - mewbie_network
networks:
  mewbie_network:
    driver: bridge
