---

# Make sure these add up to 100
Databases: 
  MongoDB: 
    percentage: 30 
  Redis: 
    percentage: 30
  Postgres: 
    percentage: 40

WorkloadConfig:
  record_count: 1000          # eg: 1000 
  record_size_dist: 'uniform'      # eg: uniform, lognormal
  data_access_pattern: 'zipfian'    # eg: zipfian, uniform
  rw_ratio: 0.5               # eg: 0.5
  async_sync_ratio: 0.1

# Make sure these add up to 100
SLTypeSplit:
  Relay:
    percentage: 30
  High:
    percentage: 20
  Low:
    percentage: 50




