---

# Make sure these add up to 100
Databases: 
  MongoDB: 
    percentage: 20 
  Redis: 
    percentage: 20
  Postgres: 
    percentage: 60

WorkloadConfig:
  record_count: 1000          # eg: 1000 
  record_size_dist: 'uniform'      # eg: uniform, lognormal
  data_access_pattern: 'zipfian'    # eg: uniform, zipfian
  rw_ratio: 1               # eg: 0.5
  async_sync_ratio: 0.1

ExpWorkloadName: test_run
## Datastore mixtures: dmix1_pg_heavy, dmix2_mongo_heavy, dmix3_redis_heavy
## Consistency exp: consistency_exp
## Testing: test_run
