---

# Make sure these add up to 100
Databases: 
  MongoDB: 
    percentage: 10
    consistency: 'eventual'  # strong, eventual
  Redis: 
    percentage: 10
  Postgres: 
    percentage: 80
    consistency: 'strong'  # strong, eventual

WorkloadConfig:
  record_count: 1000          # eg: 1000 
  record_size_dist: 'uniform'      # eg: uniform, lognormal
  data_access_pattern: 'zipfian'    # eg: uniform, zipfian
  rw_ratio: 1              # eg: 0.5
  async_sync_ratio: 2



ExpWorkloadName: test_run
 # for dmix exps keep both same

## Datastore mixtures: dmix1_pg_heavy, dmix2_mongo_heavy, dmix3_redis_heavy
## Consistency exp: consistency_exp
## Testing: test_run
# All dbmix and consistency experiements are run with async_sync_ratio = 1
# Async/Sync experiments are run with pg:mg:re :: 40:40:20