---

# Make sure these add up to 100
Databases: 
  MongoDB: 
    percentage: 60 
  Redis: 
    percentage: 20
  Postgres: 
    percentage: 20

WorkloadConfig:
  record_count: 1000          # eg: 1000 
  record_size_dist: 'uniform'      # eg: uniform, lognormal
  data_access_pattern: 'zipfian'    # eg: uniform, zipfian
  rw_ratio: 1               # eg: 0.5
  async_sync_ratio: 0.5

# Make sure these add up to 100


